google_analytics: UA-177084571-1
permalink: pretty

# Set default front matter for Markdown files
defaults:
  -
    scope:
      path: "" # All files
    values:
      layout: default
      image: assets/images/og-image.png # Social media preview
      lang: en

  # Set URLs and language code for collections
  # English   
  -
    scope:
      path: _homepage/en/index.md
    values:
      permalink: / # Set as index
  -
    scope:
      path: _pages/en
    values:
      permalink: /:title
  # Spanish
  -
    scope:
      path: _homepage/es/index.md
    values:
      permalink: /es/
      image: "assets/images/og-image-es.png"
      lang: es
  -
    scope:
      path: _pages/es
    values:
      permalink: es/:title # language-specific folder
      image: "assets/images/og-image-es.png"
      lang: es

# Manage lists of content with collections
# https://jekyllrb.com/docs/collections/
collections:
  # Homepage translations
  homepage:
    output: true
  pages:
    output: true
