title: Chicago Tenants Movement
description: Know your rights as a tenant, and get help in your neighborhood. 
google_analytics: UA-177084571-1
permalink: pretty

# Set default front matter for Markdown files
defaults:
  -
    scope:
      path: "" # All files
    values:
      layout: default
      image: "assets/images/og-image.png"

# Manage lists of content with collections
# https://jekyllrb.com/docs/collections/
collections:
  translations:
    output: true
    permalink: /:path/
