title: Chicago Tenants Movement
description: Portal with a directory of legal resources and community contacts.
google_analytics:
permalink: pretty

# Add content here to enable a site-wide, top banner
banner:
  text: "**Here's a banner:** you can turn it off/on, add styling, and link to other pages"
  link: /

# Set default front matter for Markdown files
defaults:
  -
    scope:
      path: "" # All files
    values:
      layout: default
      image: ""
