title: Chicago Tenants Movement
description: Portal with a directory of legal resources and community contacts.
google_analytics:
permalink: pretty

# Set default front matter for Markdown files
defaults:
  -
    scope:
      path: "" # All files
    values:
      layout: default
      image: "assets/images/og-image.png"

# Manage lists of content with collections
# https://jekyllrb.com/docs/collections/
collections:
  translations:
    output: true
    permalink: /:path/
